name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yml'

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: docker
        push: true
        tags: ghcr.io/${{github.actor}}/pandoc-ide:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
